[2023-08-18T02:01:32.024+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T02:01:31.439500+00:00 [queued]>
[2023-08-18T02:01:32.032+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T02:01:31.439500+00:00 [queued]>
[2023-08-18T02:01:32.033+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-18T02:01:32.042+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-08-18 02:01:31.439500+00:00
[2023-08-18T02:01:32.046+0000] {standard_task_runner.py:57} INFO - Started process 2614 to run task
[2023-08-18T02:01:32.050+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_***_dag', 'spark_submit_task', 'manual__2023-08-18T02:01:31.439500+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/spark_jobs_dag.py', '--cfg-path', '/tmp/tmp9n_4_lwe']
[2023-08-18T02:01:32.051+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask spark_submit_task
[2023-08-18T02:01:32.099+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T02:01:31.439500+00:00 [running]> on host 15ea5e9ca941
[2023-08-18T02:01:32.165+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_***_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-18T02:01:31.439500+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-18T02:01:31.439500+00:00'
[2023-08-18T02:01:32.176+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-08-18T02:01:32.177+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --name arrow-spark ./dags/utils/spark_processing.py
[2023-08-18T02:01:32.262+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-08-18T02:01:34.344+0000] {spark_submit.py:491} INFO - Traceback (most recent call last):
[2023-08-18T02:01:34.345+0000] {spark_submit.py:491} INFO - File "/opt/***/dags/utils/spark_processing.py", line 4, in <module>
[2023-08-18T02:01:34.346+0000] {spark_submit.py:491} INFO - from pandas import pd
[2023-08-18T02:01:34.347+0000] {spark_submit.py:491} INFO - ImportError: cannot import name 'pd' from 'pandas' (/home/***/.local/lib/python3.10/site-packages/pandas/__init__.py)
[2023-08-18T02:01:34.412+0000] {spark_submit.py:491} INFO - 23/08/18 02:01:34 INFO ShutdownHookManager: Shutdown hook called
[2023-08-18T02:01:34.414+0000] {spark_submit.py:491} INFO - 23/08/18 02:01:34 INFO ShutdownHookManager: Deleting directory /tmp/spark-581223c6-6bfa-4d99-8e11-378cf8db5841
[2023-08-18T02:01:34.450+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark ./dags/utils/spark_processing.py. Error code is: 1.
[2023-08-18T02:01:34.454+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=spark_***_dag, task_id=spark_submit_task, execution_date=20230818T020131, start_date=20230818T020132, end_date=20230818T020134
[2023-08-18T02:01:34.463+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task spark_submit_task (Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark ./dags/utils/spark_processing.py. Error code is: 1.; 2614)
[2023-08-18T02:01:34.505+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-18T02:01:34.523+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
